# Generated by Django 5.0.7 on 2024-09-15 16:39

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('profile_image', models.ImageField(default='static/images/default_avatar.png', upload_to='accounts/media/images')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('afghanistan', 'Afghanistan'), ('albania', 'Albania'), ('algeria', 'Algeria'), ('andorra', 'Andorra'), ('angola', 'Angola'), ('antigua and barbuda', 'Antigua and Barbuda'), ('argentina', 'Argentina'), ('armenia', 'Armenia'), ('australia', 'Australia'), ('austria', 'Austria'), ('azerbaijan', 'Azerbaijan'), ('bahamas', 'Bahamas'), ('bahrain', 'Bahrain'), ('bangladesh', 'Bangladesh'), ('barbados', 'Barbados'), ('belarus', 'Belarus'), ('belgium', 'Belgium'), ('belize', 'Belize'), ('benin', 'Benin'), ('bhutan', 'Bhutan'), ('bolivia', 'Bolivia'), ('bosnia and herzegovina', 'Bosnia and Herzegovina'), ('botswana', 'Botswana'), ('brazil', 'Brazil'), ('brunei', 'Brunei'), ('bulgaria', 'Bulgaria'), ('burkina faso', 'Burkina Faso'), ('burundi', 'Burundi'), ('cabo verde', 'Cabo Verde'), ('cambodia', 'Cambodia'), ('cameroon', 'Cameroon'), ('canada', 'Canada'), ('central african republic', 'Central African Republic'), ('chad', 'Chad'), ('chile', 'Chile'), ('china', 'China'), ('colombia', 'Colombia'), ('comoros', 'Comoros'), ('congo, democratic republic of the', 'Congo, Democratic Republic of the'), ('congo, republic of the', 'Congo, Republic of the'), ('costa rica', 'Costa Rica'), ('croatia', 'Croatia'), ('cuba', 'Cuba'), ('cyprus', 'Cyprus'), ('czech republic', 'Czech Republic'), ('denmark', 'Denmark'), ('djibouti', 'Djibouti'), ('dominica', 'Dominica'), ('dominican republic', 'Dominican Republic'), ('ecuador', 'Ecuador'), ('egypt', 'Egypt'), ('el salvador', 'El Salvador'), ('equatorial guinea', 'Equatorial Guinea'), ('eritrea', 'Eritrea'), ('estonia', 'Estonia'), ('eswatini', 'Eswatini'), ('ethiopia', 'Ethiopia'), ('fiji', 'Fiji'), ('finland', 'Finland'), ('france', 'France'), ('gabon', 'Gabon'), ('gambia', 'Gambia'), ('georgia', 'Georgia'), ('germany', 'Germany'), ('ghana', 'Ghana'), ('greece', 'Greece'), ('grenada', 'Grenada'), ('guatemala', 'Guatemala'), ('guinea', 'Guinea'), ('guinea-bissau', 'Guinea-Bissau'), ('guyana', 'Guyana'), ('haiti', 'Haiti'), ('honduras', 'Honduras'), ('hungary', 'Hungary'), ('iceland', 'Iceland'), ('india', 'India'), ('indonesia', 'Indonesia'), ('iran', 'Iran'), ('iraq', 'Iraq'), ('ireland', 'Ireland'), ('israel', 'Israel'), ('italy', 'Italy'), ('jamaica', 'Jamaica'), ('japan', 'Japan'), ('jordan', 'Jordan'), ('kazakhstan', 'Kazakhstan'), ('kenya', 'Kenya'), ('kiribati', 'Kiribati'), ('kosovo', 'Kosovo'), ('kuwait', 'Kuwait'), ('kyrgyzstan', 'Kyrgyzstan'), ('laos', 'Laos'), ('latvia', 'Latvia'), ('lebanon', 'Lebanon'), ('lesotho', 'Lesotho'), ('liberia', 'Liberia'), ('libya', 'Libya'), ('liechtenstein', 'Liechtenstein'), ('lithuania', 'Lithuania'), ('luxembourg', 'Luxembourg'), ('madagascar', 'Madagascar'), ('malawi', 'Malawi'), ('malaysia', 'Malaysia'), ('maldives', 'Maldives'), ('mali', 'Mali'), ('malta', 'Malta'), ('marshall islands', 'Marshall Islands'), ('mauritania', 'Mauritania'), ('mauritius', 'Mauritius'), ('mexico', 'Mexico'), ('micronesia', 'Micronesia'), ('moldova', 'Moldova'), ('monaco', 'Monaco'), ('mongolia', 'Mongolia'), ('montenegro', 'Montenegro'), ('morocco', 'Morocco'), ('mozambique', 'Mozambique'), ('myanmar', 'Myanmar'), ('namibia', 'Namibia'), ('nauru', 'Nauru'), ('nepal', 'Nepal'), ('netherlands', 'Netherlands'), ('new zealand', 'New Zealand'), ('nicaragua', 'Nicaragua'), ('niger', 'Niger'), ('nigeria', 'Nigeria'), ('north korea', 'North Korea'), ('north macedonia', 'North Macedonia'), ('norway', 'Norway'), ('oman', 'Oman'), ('pakistan', 'Pakistan'), ('palau', 'Palau'), ('palestine', 'Palestine'), ('panama', 'Panama'), ('papua new guinea', 'Papua New Guinea'), ('paraguay', 'Paraguay'), ('peru', 'Peru'), ('philippines', 'Philippines'), ('poland', 'Poland'), ('portugal', 'Portugal'), ('qatar', 'Qatar'), ('romania', 'Romania'), ('russia', 'Russia'), ('rwanda', 'Rwanda'), ('saint kitts and nevis', 'Saint Kitts and Nevis'), ('saint lucia', 'Saint Lucia'), ('saint vincent and the grenadines', 'Saint Vincent and the Grenadines'), ('samoa', 'Samoa'), ('san marino', 'San Marino'), ('sao tome and principe', 'Sao Tome and Principe'), ('saudi arabia', 'Saudi Arabia'), ('senegal', 'Senegal'), ('serbia', 'Serbia'), ('seychelles', 'Seychelles'), ('sierra leone', 'Sierra Leone'), ('singapore', 'Singapore'), ('slovakia', 'Slovakia'), ('slovenia', 'Slovenia'), ('solomon islands', 'Solomon Islands'), ('somalia', 'Somalia'), ('south africa', 'South Africa'), ('south korea', 'South Korea'), ('south sudan', 'South Sudan'), ('spain', 'Spain'), ('sri lanka', 'Sri Lanka'), ('sudan', 'Sudan'), ('suriname', 'Suriname'), ('sweden', 'Sweden'), ('switzerland', 'Switzerland'), ('syria', 'Syria'), ('taiwan', 'Taiwan'), ('tajikistan', 'Tajikistan'), ('tanzania', 'Tanzania'), ('thailand', 'Thailand'), ('timor-leste', 'Timor-Leste'), ('togo', 'Togo'), ('tonga', 'Tonga'), ('trinidad and tobago', 'Trinidad and Tobago'), ('tunisia', 'Tunisia'), ('turkey', 'Turkey'), ('turkmenistan', 'Turkmenistan'), ('tuvalu', 'Tuvalu'), ('uganda', 'Uganda'), ('ukraine', 'Ukraine'), ('united arab emirates', 'United Arab Emirates'), ('united kingdom', 'United Kingdom'), ('united states', 'United States'), ('uruguay', 'Uruguay'), ('uzbekistan', 'Uzbekistan'), ('vanuatu', 'Vanuatu'), ('vatican city', 'Vatican City'), ('venezuela', 'Venezuela'), ('vietnam', 'Vietnam'), ('yemen', 'Yemen'), ('zambia', 'Zambia'), ('zimbabwe', 'Zimbabwe')], max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('zip_code', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userAddress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
