# Generated by Django 5.0.7 on 2024-09-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_brith',
            field=models.DateField(blank=True, null=True),
        ),
    ]
