# Generated by Django 5.0.7 on 2024-09-14 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_specialization_journalist_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalist',
            old_name='Awards',
            new_name='awards',
        ),
    ]
