# Generated by Django 5.0.7 on 2024-09-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_specialization_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
